storage:
  block_size: 4096
  bucket_size: 8
  tree_height: 20
  use_file_backend: false
  data_dir: data
  data_file_size: 1073741824

network:
  down_bw_bytes_per_sec: 104857600
  up_bw_bytes_per_sec: 104857600
  rtt_sec: 0.001

crypto:
  enc_bytes_per_sec: 2000000000
  dec_bytes_per_sec: 2000000000

server_io:
  bucket_read_sec: 0.004
  bucket_write_sec: 0.004

ring:
  s_num: 12
  a_num: 8

atom:
  lambda1: 1.0
  tick_interval_sec: 0.01
  queue_limit: 100000